### ISSUE TITLE
Bug反馈

### ISSUE THREAD

**Issue by lqx0302** [SurviveFDYZ/survivefdyz.github.io#1]
每次返回到前言 小方块都会变多
![Screenshot_2024-08-29-18-50-11-872_mark via](https://github.com/user-attachments/assets/5dd5c8f2-be6a-40d8-92ef-ee8dbaa95cfe)

（刚好用这个机会测试一下github的issue

**Comment by Eagle233Fake** [comment]
太细节了，我也发现了。但是这个我暂时也无法得知原因，我之后把他改成别的形式吧。
fixed: https://github.com/SurviveFDYZ/survivefdyz.github.io/commit/b073c19fe6040e6dcf8bcfc3aba84420e9894019
